### ISSUE TITLE
Switching contexts using kcs affects all terminals

### ISSUE THREAD

**Issue by scottslowe** [lowescott/scripts#8]
Because `kcs` is manipulating files in the `~/.kube` directory (by default), it's not possible to have one Kubernetes context in one terminal and a different Kubernetes context in a different terminal. I don't think is any workaround at this time.

**Comment by rninov** [comment]
IMHO that's possible if you have more than one directory with configs. And use command line to define which one to use (if not selected will be used default one). Do you want me to draft this idea?

**Comment by scottslowe** [comment]
AIUI moving to multiple directories would also involve setting the `KUBECONFIG` environment variable, and if we're going to go down that route then we don't need multiple directories at all (we could just set `KUBECONFIG` to a file in the default `$HOME/.kube` directory. That being said, if you'd like to explore the idea and submit a PR for consideration, that'd be great. Thanks!

**Comment by scottslowe** [comment]
I'm closing this issue as the `kcs` functionality I'm seeking is provided by `ktx` (https://github.com/heptiolabs/ktx/).
